# Generated by Django 2.2.2 on 2019-11-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_type_materiel', models.PositiveSmallIntegerField(verbose_name='numéro Materiel')),
                ('type_materiel', models.CharField(choices=[('ORDINATEUR', 'ORDINATEUR'), ('IMPRIMANT', 'IMPRIMANT'), ('SCANNER', 'SCANNER'), ('PHOTOCOPIEUSE', 'PHOTOCOPIEUSE'), ('PERIPHERIQUE', 'PERIPHERIQUE'), ('MONITEUR', 'MONITEUR')], default=[0], max_length=100, verbose_name='type de materiel')),
                ('composant', models.CharField(choices=[('ECRAN', 'ECRAN'), ('SYSTEME', 'SYSTEME'), ('LOGICIEL', 'LOGICIEL'), ('RAM', 'RAM'), ('SOURIS', 'SOURIS'), ('CLAVIER', 'CLAVIER')], default=[0], max_length=100, verbose_name='Les caracteristiques du materiel')),
            ],
            options={
                'verbose_name': 'Type_materiel',
                'verbose_name_plural': 'Types_materiels',
            },
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='nom materiel')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='numéro Materiel')),
                ('numero_serie', models.PositiveSmallIntegerField(verbose_name='numero_serie Materiel')),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureau', to='service.Bureau')),
            ],
            options={
                'verbose_name': 'Materiel',
                'verbose_name_plural': 'Materiels',
            },
        ),
       
    ]
