# Generated by Django 2.2.2 on 2019-12-21 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materiel',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='type_materiel',
            name='Id_type_materiel',
        ),
        migrations.RemoveField(
            model_name='type_materiel',
            name='composant',
        ),
        migrations.RemoveField(
            model_name='type_materiel',
            name='type_materiel',
        ),
        migrations.AddField(
            model_name='materiel',
            name='caracteristique',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='caracteristique'),
        ),
        migrations.AddField(
            model_name='materiel',
            name='type_materiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_materiel', to='parc.Type_materiel'),
        ),
        migrations.AddField(
            model_name='type_materiel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='type_materiel',
            name='libelle_materiel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='libelle type_materiel'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bureau', to='service.Bureau'),
        ),
        migrations.AlterField(
            model_name='materiel',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='numero_serie Materiel'),
        ),
    ]
