# Generated by Django 2.2.2 on 2020-01-13 16:52

import blog.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(validators=[blog.models.validate_message_content])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
