# Generated by Django 2.2.2 on 2020-01-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Degre '),
        ),
    ]
