# Generated by Django 2.2.2 on 2019-11-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bureau',
            name='id_bureau',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='id_dep',
        ),
        migrations.RemoveField(
            model_name='intervenant',
            name='id_intervenant',
        ),
        migrations.AlterField(
            model_name='bureau',
            name='num_bureau',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='numéro du Bureau'),
        ),
    ]
