# Generated by Django 2.2.2 on 2019-12-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191117_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='service.Departement'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='libelle_dep',
            field=models.CharField(blank=True, choices=[('COMPTABILITE', 'COMPTABILITE'), ('COMMUNICATION', 'COMMUNICATION'), ('INFORMATIQUE', 'INFORMATIQUE'), ('MARKETING', 'MARKETING'), ('RESEAUX', 'RESEAUX')], max_length=100, null=True, verbose_name='Libelle du departement'),
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='couriel'),
        ),
        migrations.AlterField(
            model_name='intervenant',
            name='nom_intervenant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="nom de l'intervenant"),
        ),
    ]
