# Generated by Django 2.2.2 on 2019-12-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20191211_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departement', to='service.Departement'),
        ),
    ]
