# Generated by Django 2.2.2 on 2019-12-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20191219_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bureau',
            name='num_bureau',
            field=models.IntegerField(blank=True, null=True, verbose_name='numéro du Bureau'),
        ),
    ]
