# Generated by Django 2.2.2 on 2019-11-06 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parc', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_interv', models.CharField(blank=True, max_length=100, null=True, verbose_name="libelle de l'intervention")),
                ('num_interv', models.PositiveSmallIntegerField(verbose_name="numéro de l' intervention")),
                ('date_interv', models.DateTimeField(blank=True, null=True, verbose_name="date de l'intervention")),
                ('accomplie', models.BooleanField(blank=True, null=True, verbose_name='Statut de la panne')),
                ('type_interv', models.CharField(choices=[('EN PERSONNE', 'EN PERSONNE'), ('EN RESEAU', 'EN RESEAU')], default=[0], max_length=100, verbose_name="type de l'intervention")),
                ('consigne', models.CharField(blank=True, max_length=100, null=True, verbose_name='consigne de la panne ')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
            },
        ),
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='description de la panne')),
                ('id_pan', models.PositiveSmallIntegerField(verbose_name='identifiant de la panne')),
                ('intervenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Intervenant', verbose_name='intervenant')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parc.Materiel', verbose_name=' materiel')),
            ],
            options={
                'verbose_name': 'Panne',
                'verbose_name_plural': 'Pannes',
            },
        ),
        migrations.CreateModel(
            name='Type_panne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='designation du type de panne')),
                ('id_type_pan', models.PositiveSmallIntegerField(verbose_name='Identifiant du type de panne')),
                ('libelle_pan', models.CharField(choices=[('SYSTEME', 'SYSTEME'), ('LOGICIEL', 'LOGICIEL'), ('MATERIEL', 'MATERIEL'), ('CONNEXION', 'CONNEXION')], default=[0], max_length=100, verbose_name='libelle de la panne')),
                ('panne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panne', to='intervention.Panne')),
            ],
            options={
                'verbose_name': 'Type_panne',
                'verbose_name_plural': 'Types_pannes',
            },
        ),
    ]
