# Generated by Django 2.2.2 on 2019-11-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20191117_1829'),
        ('intervention', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='num_interv',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='id_pan',
        ),
        migrations.RemoveField(
            model_name='type_panne',
            name='id_type_pan',
        ),
        migrations.RemoveField(
            model_name='type_panne',
            name='panne',
        ),
        migrations.AddField(
            model_name='intervention',
            name='intervenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Intervenant', verbose_name='intervenant'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='panne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intervention.Panne', verbose_name='panne'),
        ),
        migrations.AddField(
            model_name='panne',
            name='type_panne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_panne', to='intervention.Type_panne'),
        ),
        migrations.AlterField(
            model_name='panne',
            name='intervenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Intervenant', verbose_name='intervenant'),
        ),
        migrations.AlterField(
            model_name='panne',
            name='materiel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parc.Materiel', verbose_name='materiel'),
        ),
    ]
