# Generated by Django 2.2.2 on 2020-01-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0004_panne_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panne',
            name='niveau',
            field=models.CharField(blank=True, choices=[('HAUTE', 'HAUTE'), ('MOYENNE ', 'MOYENNE '), ('FAIBLE', 'FAIBLE')], default=[0], max_length=100, null=True, verbose_name='Niveau de la panne'),
        ),
    ]
